# Generated by Django 4.2.17 on 2025-04-20 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
